### ISSUE TITLE
FIle upload

### ISSUE THREAD

**Issue by Adrian-Rae-19004029** [COS301-SE-2021/Midi-Interpretation#7]
The mechanism for uploading files doesn't seem to be compatible with the React fetch method. It either seems as if there is no file or the method for encoding it in multipart form data ignores the boundary. Either way, I get a 415 from invalid data type if I let React decide (as the backend expects multipart and is compatible with Swagger's upload interface) or a 500 from the server not being able to discern a multipart boundary.

**Comment by HendroSmit** [comment]
Has been fixed by including a react-dropbox-uploader module to handle the file boundaries
